#!/bin/bash

EDITOR=/usr/bin/vim
HISTCONTROL=ignoreboth
WORK="${HOME}/${WORKNAME}"
PERSONAL="${HOME}/personal-projects"
HISTSIZE=1000
HISTFILESIZE=2000
FOREGROUND_COLOR=#EFEFEF
BACKGROUND_COLOR=#303030
export GOROOT=/usr/local/go